SiteConfig:
  extensions:
    - PocketwatchSiteConfig
BlogPost:
  extensions:
    - BlogPostExtension
Blog:
  extensions:
    - BlogExtension
#BlogAdminSidebar:
#  extensions:
#    - BlogAdminSidebarExtension